# Generated by Django 5.0.6 on 2024-06-17 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('verb', models.IntegerField(choices=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post')], help_text=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post')], null=True)),
                ('sender_object_id', models.PositiveIntegerField(null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
