# Generated by Django 5.0.6 on 2024-06-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post'), (4, 'New Giz')], help_text=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post'), (4, 'New Giz')], null=True),
        ),
    ]
