# Generated by Django 5.0.6 on 2024-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post')], help_text=[(1, 'Follow'), (2, 'New Post'), (3, 'Like Post')], null=True),
        ),
    ]
