from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='item_category'),
    path('category/', views.CategoryView.as_view(), name='item_category'),
    path('interest_category/', views.InterestCategoryView.as_view(), name='interest_category'),
    path('topic/', views.TopicView.as_view(), name='topic'),
    path('custom_topic/', views.CustomTopicView.as_view(), name='custom_topic'),
    path('interest_topic/', views.InterestTopicView.as_view(), name='interest_topic'),
    path('post/', views.PostView.as_view(), name='post'),
    path('post/<int:id>/', views.PostEditView.as_view(), name='post'),
    path('comment/', views.CommentView.as_view(), name='comment'),
    path('post/like/', views.PostLikeView.as_view(), name='add_like'),
    path('post/like/<int:id>/', views.PostUnlikeView.as_view(), name='add_like'),
    path('comment/like/', views.CommentLikeView.as_view(), name='comment_like'),
    path('comment/like/<int:id>/', views.CommentUnlikeView.as_view(), name='comment_unlike'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('follow/<int:id>/', views.FollowDetailView.as_view(), name='follow'),
    path('post/view/', views.PostViewerView.as_view(), name='post_view'),
    path('bookmark/', views.BookmarkView.as_view(), name='bookmark'),
    path('bookmark/<int:id>/', views.EditBookmarkView.as_view(), name='edit_bookmark'),
    path('review/', views.ReviewView.as_view(), name='review'),
    path('review/<int:pk>/', views.EditReviewView.as_view(), name='edit_review'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/<int:id>/', views.RemoveCartView.as_view(), name='cart'),
    path('address/', views.AddressView.as_view(), name='address'),
    path('address/<int:pk>/', views.EditAddressView.as_view(), name='edit_address'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('order/<int:pk>/', views.EditOrderView.as_view(), name='edit_order'),
    path('user/post/category/', views.UserPostCategoryView.as_view(), name='interested_post_topic'),
    path('user/post/topic/', views.UserPostTopicView.as_view(), name='interested_post_topic'),
    path('filter/category/', views.CategoryFilterView.as_view(), name='filter_category'),
    path('organization/', views.OrganizationDetailView.as_view(), name='organization'),
    path('post/follower/', views.PostFollowerView.as_view(), name='post_follower'),
    path('post/interest/', views.PostInterestView.as_view(), name='post_interest'),
    path('post_notification/<uidb64>/', views.PostDetailView.as_view(), name='post_notification'),
    path('post-report/', views.PostReportView.as_view(), name='post_report'),
    path('comment-report/', views.CommentReportView.as_view(), name='comment_report'),
    path('download/', views.DownloadView.as_view(), name='download'),
]
